### ISSUE TITLE
ERROR: Service 'nginxplus' failed to build: lstat nginx-repo.crt: no such file or directory

### ISSUE THREAD

**Issue by naren970** [nginxinc/NGINX-Demos#1]
Hi Kunal,

I'm trying execute the demo **consul-dns-srv-demo** and Its very nice post and followed in manul installation section to excute the demo, and executed all the steps from 1 and strucked in step 6 and got error while building nginxplus image, I've attached screen shot. So I when I ran command "docker ps" to know the images which are up and running, I didn't any list like you showed in Running Demo screen.

BTW, I'm using Ubuntu 14.04 and installed docker-tools & docker-compose.

Am I following right way to execute the demo?
Can you please help me to execute the demo

![ngnixerror](https://cloud.githubusercontent.com/assets/5229168/16902722/bf1ee06a-4c84-11e6-929b-031d8b639672.PNG)

**Comment by kunalvjti** [comment]
You are missing the nginx-repo.crt file which needs to be placed under ~/NGINX-Demos/consul-dns-srv-demo/nginxplus/ directory as per step 2 of the Manual install instructions. You need to signup for a free 30-day [NGINX Plus trial](https://www.nginx.com/#free-trial) in order to download the nginx-repo.crt/.key files.

**Comment by naren970** [comment]
Ohh my bad,  I missed that,
Thanks for helping Kunal,

After adding files in nginxplus folder all containers able to create, but at the end Im getting error, which is attached image,
I'm using docker 1.11 and docker-compose1.7 
Is version missmatch the problem? 
![dockererro](https://cloud.githubusercontent.com/assets/5229168/16905455/cd072e3c-4cc3-11e6-954a-8ab528dc260e.PNG)

**Comment by kunalvjti** [comment]
This seems to be an issue with the docker-compose version you are running (check this https://github.com/docker/compose/issues/3432). Please update to the latest version and check if that fixes the issue
