### ISSUE TITLE
nginx-regex-tester bugs: Undefined index: frmCaseSensitive & readme typo

### ISSUE THREAD

**Issue by centminmod** [nginxinc/NGINX-Demos#22]
For https://github.com/nginxinc/NGINX-Demos/tree/master/nginx-regex-tester, the docker container's logs report following error

```
docker logs regextester

2019/06/12 03:23:26 [notice] 17#17 php message: PHP Notice:  Undefined index: frmCaseSensitive in /usr/share/nginx/html/regextester.php on line 97
```

also readme has typo missing hyphen

typo

> Setup
> From /nginx-regextester: # docker-compose up -d

should be directory at `nginx-regex-tester`

> Setup
> From /nginx-regex-tester: # docker-compose up -d

**Comment by tienidurodad** [comment]
Good catches.  They have been fixed.
