### ISSUE TITLE
packer-terraform-all-active-nginx-plus-lb missing from master

### ISSUE THREAD

**Issue by mjmenger** [nginxinc/NGINX-Demos#24]
it's still in the README. Should the README be updated or the directories pulled into master from the whisper branches?

**Comment by jfreeland** [comment]
https://github.com/nginxinc/NGINX-Demos/commit/99449878f4a2a8d3473a7277800e7401ded9225a#commitcomment-34644970

Looks like it was accidental.

**Comment by alessfg** [comment]
Demo is still there, but it was renamed to `gcp-lb-ha-asg`. I will update the blog post referring to the demo as soon as possible.

**Comment by alessfg** [comment]
All references have been updated to the best of my knowledge 😄
