### ISSUE TITLE
nginx-regex-tester broken running on Windows due to line endings

### ISSUE THREAD

**Issue by spatel96** [nginxinc/NGINX-Demos#37]
Steps to reproduce:

1. Clone the repository
2. Run a docker-compose up

The container will fail to start with the follow error:
```
docker-compose.exe logs -f
Attaching to regextester
regextester    | /docker-entrypoint.sh: 38: exec: /usr/local/sbin/start.sh: not found
regextester exited with code 127
```

From running a shell within the container:
```
root@28e3903efd0b:/usr/local/sbin# ls
start.sh
root@28e3903efd0b:/usr/local/sbin# ./start.sh
bash: ./start.sh: /bin/sh^M: bad interpreter: No such file or directory
```

I have worked around this by setting LF line endings for the start.sh file and ensuring the path is shared via Docker for Windows.

**Comment by PhalanxHead** [comment]
Can this solution be documented in the `nginx-regex-tester` readme?
I just spent like an hour trying to debug this :'(

**Comment by lucacome** [comment]
@spatel96 @PhalanxHead https://github.com/nginxinc/NGINX-Demos/pull/63 should fix this, but I don't have a Windows machine to test it 🤞
