### ISSUE TITLE
Require image for ARM64 architecture

### ISSUE THREAD

**Issue by odidev** [nginxinc/NGINX-Demos#41]
Hi Team, 

I am trying to use the **nginxdemos/hello** image on arm64 platform but it seems it is not available for arm64.
 
I have successfully built the image using the command **docker build -t image_name .** on the arm64 platform without making any changes in the Dockerfile.
 
I have used **Travis-CI** to build and push the image for both the platforms. 

**Commit Link -** https://github.com/odidev/NGINX-Demos/commit/83ee65ed322fcde939bd169524df295d3d1759d6 

**Travis-CI link -** https://travis-ci.com/github/odidev/NGINX-Demos/builds/233410934 

**Docker Hub Link -** https://hub.docker.com/repository/registry-1.docker.io/odidev/nginxdemos_hello/tags?page=1&ordering=last_updated 

Do you have any plans on releasing arm64 images? 

It will be very helpful if arm64 image is available. If interested, I will raise a PR.

**Comment by lucacome** [comment]
Hi @odidev 

the image for `nginxdemos/hello` was just built and pushed for arm64 (and other architectures). Let me know if everything is running smoothly 🙂
